/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
static yyconst short int yy_accept[233] =
    {   0,
        0,    0,    0,    0,    0,    0,   83,   81,   79,   80,
       34,   65,   36,   40,   81,   44,   45,   32,   30,   52,
       31,   81,   33,   55,   55,   55,   48,   49,   39,   37,
       38,   43,   58,   46,   47,   42,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   50,   41,   51,   35,   76,   77,   76,   76,   72,
       67,   66,   72,   23,   24,    0,    0,   21,   59,   74,
       73,    0,   55,   55,   57,    0,   28,   27,   22,   26,
       29,   58,   58,   58,   58,   58,   58,   58,   11,   58,
       58,   58,   58,   58,   15,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   25,   78,   75,   68,    0,
        0,    0,   64,    0,   64,    0,    0,    0,    0,   73,
       56,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,    5,   58,   58,   58,   58,   58,   58,   58,   58,
       58,    0,    0,    0,   60,    0,    0,    0,    0,   59,
        2,   58,    9,    3,   58,   12,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   53,   58,    7,   58,    0,
        0,   71,    0,    0,    0,    8,   58,   58,   54,    4,
       58,   16,   58,   58,    1,   58,   58,   20,    0,   70,
        0,    0,   63,   58,   13,   58,   17,   18,   19,   58,

        0,    0,   62,   10,   58,    6,    0,    0,   58,    0,
        0,   58,    0,    0,   58,   69,    0,   58,   61,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       14,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   27,   27,   29,   27,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       31,   32,   33,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   30,   45,   46,   47,   48,
       49,   50,   30,   51,   52,   53,   54,   55,   56,   57,
       58,   30,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    5,    4,    6,
        1,    1,    1,    1,    6,    5,    5,    4,    4,    4,
        5,    6,    6,    6,    6,    6,    6,    7,    7,    6,
        7,    6,    7,    6,    7,    6,    7,    6,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[246] =
    {   0,
        0,    0,   60,   61,   62,   63,  224,  945,  945,  945,
      180,  945,  945,  188,  153,  945,  945,  945,  945,  945,
      123,   61,   58,   68,   82,   89,  945,  945,   66,  120,
       67,  945,   94,  945,  945,  945,   98,  103,  110,  114,
      118,  123,  138,  148,  156,  163,  170,  174,  179,  189,
      193,  945,   66,  945,  945,  945,  945,   87,   87,  945,
      945,  945,   96,  945,  945,   85,  192,  945,  199,  945,
        0,  212,  225,  237,  945,    0,  945,  945,  945,  945,
      945,    0,  241,  246,  250,  254,  258,  262,  266,  279,
      290,  294,  298,  302,  306,  310,  315,  319,  331,  342,

      347,  351,  355,  362,  368,  945,  945,  945,  945,  134,
      144,    0,  945,   76,   74,  152,  216,    0,  378,    0,
        0,  382,  396,  400,  404,  416,  424,  428,  439,  443,
      452,  456,  463,  467,  475,  479,  487,  491,  495,  499,
      505,  160,  229,    0,  945,  184,  270,    0,  515,  524,
      528,  537,  541,  545,  549,  553,  557,  561,  566,  570,
      574,  578,  592,  596,  608,  612,  616,  620,  633,  197,
      274,  945,  204,  283,   67,  637,  641,  645,  650,  657,
      661,  665,  671,  677,  683,  687,  695,  699,  233,  945,
      287,   65,  945,  703,  709,  714,  719,  723,  727,  731,

      324,  327,  945,  735,  740,  747,  336,  339,  754,  359,
      376,  758,  386,  392,  762,  945,   62,  767,  945,  772,
      776,  780,  791,  795,  810,  814,  822,  830,  834,  838,
      842,  945,  888,  895,  902,  906,  911,  916,  923,  927,
      929,  933,  935,  937,  939
    } ;

static yyconst short int yy_def[246] =
    {   0,
      232,    1,  233,  233,  234,  234,  232,  232,  232,  232,
      232,  232,  232,  232,  235,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  236,  232,  232,  232,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  237,  232,  232,  232,  238,  232,  232,  232,
      239,  232,  232,  232,  232,  240,  232,  232,  232,  232,
      232,  241,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,

      236,  236,  236,  236,  236,  232,  232,  232,  232,  232,
      232,  242,  232,  232,  232,  232,  232,  243,  232,  239,
      240,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  232,  232,  244,  232,  232,  232,  245,  232,  232,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  232,
      232,  232,  232,  232,  232,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  232,  232,
      232,  232,  232,  236,  236,  236,  236,  236,  236,  236,

      232,  232,  232,  236,  236,  236,  232,  232,  236,  232,
      232,  236,  232,  232,  236,  232,  232,  236,  232,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,    0,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232
    } ;

static yyconst short int yy_nxt[1008] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   26,
       27,   28,   29,   30,   31,   32,   33,   33,   33,   33,
       34,    8,   35,   36,   33,   33,   37,   38,   39,   40,
       41,   42,   33,   43,   33,   44,   45,   33,   33,   33,
       46,   47,   48,   49,   50,   51,   33,   33,   52,   53,
       54,   55,   57,   57,   61,   61,   62,   62,   70,  219,
       58,   58,  203,   71,  193,   59,   59,   69,   69,   69,
       69,  145,   72,  145,   73,   73,   74,   74,   77,   78,
       80,   81,  113,   63,   63,   75,   72,  108,   73,   73,

       74,   74,  107,   72,   75,   74,   74,   74,   74,   75,
       82,   82,   82,   82,   82,   82,   82,   82,   75,   82,
       82,   82,   82,  110,   76,  106,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   86,   82,
       82,   82,   82,   79,  111,   87,   84,   68,   85,   88,
      142,  142,  112,   92,   82,   82,   82,   82,   89,   90,
      143,  143,  143,   93,   82,   82,   82,   82,  146,  146,
       91,   94,   82,   82,   82,   82,  170,  170,   95,   82,
       82,   82,   82,   97,   67,   96,   82,   82,   82,   82,
       82,   82,   82,   82,   65,   82,   82,   82,   82,  115,

      173,  173,   99,   64,   98,   82,   82,   82,   82,   82,
       82,   82,   82,  189,  189,   69,   69,   69,   69,  116,
      191,  191,  100,  232,  102,  101,  103,  119,   69,   69,
       69,   69,  147,  147,  147,  105,  232,  104,  119,   72,
      117,   73,   73,   74,   74,  171,  171,  171,  118,  201,
      201,   72,   75,   74,   74,   74,   74,   82,   82,   82,
       82,   75,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,  174,  174,  174,  123,
      190,  190,  190,  125,  122,   82,   82,   82,   82,  192,

      192,  192,  126,  202,  202,  124,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
      127,   82,   82,   82,   82,   82,   82,   82,   82,  129,
      207,  207,  128,  208,  208,  232,  130,   82,   82,   82,
       82,  133,  210,  210,  131,  211,  211,  134,   82,   82,
       82,   82,  132,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,  213,  213,  136,   82,   82,
       82,   82,  232,  135,   82,   82,   82,   82,  232,  149,
      137,  149,  214,  214,  150,  150,  150,  150,   82,   82,

       82,   82,  216,  216,  138,  140,  232,  139,  217,  217,
      232,  141,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,  232,  232,  232,  151,  232,  232,
      232,  152,   82,   82,   82,   82,  232,  232,  232,  153,
       82,   82,   82,   82,   82,   82,   82,   82,  232,  232,
      232,  155,  232,  232,  154,   82,   82,   82,   82,   82,
       82,   82,   82,  156,  232,  232,  232,  157,   82,   82,
       82,   82,   82,   82,   82,   82,  232,  232,  159,   82,
       82,   82,   82,   82,   82,   82,   82,  232,  232,  232,
      158,   82,   82,   82,   82,   82,   82,   82,   82,  232,

      160,  232,  161,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,  232,
      162,   82,   82,   82,   82,  232,  232,  232,  163,  164,
      166,  150,  150,  150,  150,  232,  232,  168,  232,  165,
      150,  150,  150,  150,   82,   82,   82,   82,  232,  232,
      169,  232,  167,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,  176,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,  232,  232,

      179,  232,  177,  232,  181,  232,  232,  178,   82,   82,
       82,   82,   82,   82,   82,   82,  232,  232,  180,  182,
      232,  232,  232,  183,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
      232,  232,  184,  232,  232,  186,  232,  232,  185,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,  187,   82,   82,   82,   82,
      232,  232,  188,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,  232,  194,   82,   82,   82,
       82,  232,  195,   82,   82,   82,   82,  232,  196,   82,

       82,   82,   82,   82,   82,   82,   82,  232,  232,  232,
      197,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,  232,  198,   82,   82,   82,   82,  199,
       82,   82,   82,   82,  200,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,  204,   82,   82,   82,   82,
      232,  232,  205,   82,   82,   82,   82,  232,  232,  206,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,  232,   82,   82,   82,   82,  209,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,

      218,  215,  232,  232,  232,  212,  220,   82,   82,   82,
       82,   82,   82,   82,   82,  222,  232,  232,  223,  232,
      232,  232,  221,  232,  232,  224,   82,   82,   82,   82,
       82,   82,   82,   82,  232,  232,  232,  225,   82,   82,
       82,   82,  232,  232,  232,  226,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,  232,  232,  227,  232,  232,  232,  228,  232,
      229,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  231,  232,  232,  232,  230,   56,   56,
       56,   56,   56,   56,   56,   60,   60,   60,   60,   60,

       60,   60,   66,  232,   66,   66,   66,   66,   66,   83,
       83,   83,   83,  109,  232,  109,  232,  109,  114,  232,
      114,  232,  114,  120,  232,  120,  120,  120,  120,  120,
      121,  121,   82,   82,   82,   82,  144,  144,  148,  148,
      172,  172,  175,  175,    7,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,

      232,  232,  232,  232,  232,  232,  232
    } ;

static yyconst short int yy_chk[1008] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,    5,    6,   23,  217,
        3,    4,  192,   23,  175,    3,    4,   22,   22,   22,
       22,  115,   24,  114,   24,   24,   24,   24,   29,   29,
       31,   31,   66,    5,    6,   24,   25,   59,   25,   25,

       25,   25,   58,   26,   24,   26,   26,   26,   26,   25,
       33,   33,   33,   33,   37,   37,   37,   37,   25,   38,
       38,   38,   38,   63,   24,   53,   39,   39,   39,   39,
       40,   40,   40,   40,   41,   41,   41,   41,   38,   42,
       42,   42,   42,   30,   63,   38,   37,   21,   37,   39,
      110,  110,   63,   41,   43,   43,   43,   43,   39,   40,
      111,  111,  111,   41,   44,   44,   44,   44,  116,  116,
       40,   42,   45,   45,   45,   45,  142,  142,   43,   46,
       46,   46,   46,   44,   15,   43,   47,   47,   47,   47,
       48,   48,   48,   48,   14,   49,   49,   49,   49,   67,

      146,  146,   46,   11,   45,   50,   50,   50,   50,   51,
       51,   51,   51,  170,  170,   69,   69,   69,   69,   67,
      173,  173,   47,    7,   48,   47,   49,   69,   72,   72,
       72,   72,  117,  117,  117,   51,    0,   50,   69,   73,
       67,   73,   73,   73,   73,  143,  143,  143,   67,  189,
      189,   74,   73,   74,   74,   74,   74,   83,   83,   83,
       83,   73,   84,   84,   84,   84,   85,   85,   85,   85,
       86,   86,   86,   86,   87,   87,   87,   87,   88,   88,
       88,   88,   89,   89,   89,   89,  147,  147,  147,   85,
      171,  171,  171,   87,   84,   90,   90,   90,   90,  174,

      174,  174,   88,  191,  191,   86,   91,   91,   91,   91,
       92,   92,   92,   92,   93,   93,   93,   93,   94,   94,
       94,   94,   95,   95,   95,   95,   96,   96,   96,   96,
       90,   97,   97,   97,   97,   98,   98,   98,   98,   92,
      201,  201,   91,  202,  202,    0,   93,   99,   99,   99,
       99,   97,  207,  207,   94,  208,  208,   98,  100,  100,
      100,  100,   96,  101,  101,  101,  101,  102,  102,  102,
      102,  103,  103,  103,  103,  210,  210,  100,  104,  104,
      104,  104,    0,   99,  105,  105,  105,  105,    0,  119,
      101,  119,  211,  211,  119,  119,  119,  119,  122,  122,

      122,  122,  213,  213,  102,  104,    0,  103,  214,  214,
        0,  105,  123,  123,  123,  123,  124,  124,  124,  124,
      125,  125,  125,  125,    0,    0,    0,  122,    0,    0,
        0,  123,  126,  126,  126,  126,    0,    0,    0,  124,
      127,  127,  127,  127,  128,  128,  128,  128,    0,    0,
        0,  126,    0,    0,  125,  129,  129,  129,  129,  130,
      130,  130,  130,  127,    0,    0,    0,  128,  131,  131,
      131,  131,  132,  132,  132,  132,    0,    0,  130,  133,
      133,  133,  133,  134,  134,  134,  134,    0,    0,    0,
      129,  135,  135,  135,  135,  136,  136,  136,  136,    0,

      131,    0,  133,  137,  137,  137,  137,  138,  138,  138,
      138,  139,  139,  139,  139,  140,  140,  140,  140,    0,
      134,  141,  141,  141,  141,    0,    0,    0,  135,  136,
      138,  149,  149,  149,  149,    0,    0,  140,    0,  137,
      150,  150,  150,  150,  151,  151,  151,  151,    0,    0,
      141,    0,  139,  152,  152,  152,  152,  153,  153,  153,
      153,  154,  154,  154,  154,  155,  155,  155,  155,  156,
      156,  156,  156,  157,  157,  157,  157,  158,  158,  158,
      158,  152,  159,  159,  159,  159,  160,  160,  160,  160,
      161,  161,  161,  161,  162,  162,  162,  162,    0,    0,

      158,    0,  155,    0,  160,    0,    0,  157,  163,  163,
      163,  163,  164,  164,  164,  164,    0,    0,  159,  161,
        0,    0,    0,  162,  165,  165,  165,  165,  166,  166,
      166,  166,  167,  167,  167,  167,  168,  168,  168,  168,
        0,    0,  163,    0,    0,  165,    0,    0,  164,  169,
      169,  169,  169,  176,  176,  176,  176,  177,  177,  177,
      177,  178,  178,  178,  178,  167,  179,  179,  179,  179,
        0,    0,  169,  180,  180,  180,  180,  181,  181,  181,
      181,  182,  182,  182,  182,    0,  177,  183,  183,  183,
      183,    0,  178,  184,  184,  184,  184,    0,  181,  185,

      185,  185,  185,  186,  186,  186,  186,    0,    0,    0,
      183,  187,  187,  187,  187,  188,  188,  188,  188,  194,
      194,  194,  194,    0,  184,  195,  195,  195,  195,  186,
      196,  196,  196,  196,  187,  197,  197,  197,  197,  198,
      198,  198,  198,  199,  199,  199,  199,  200,  200,  200,
      200,  204,  204,  204,  204,  194,  205,  205,  205,  205,
        0,    0,  196,  206,  206,  206,  206,    0,    0,  200,
      209,  209,  209,  209,  212,  212,  212,  212,  215,  215,
      215,  215,    0,  218,  218,  218,  218,  205,  220,  220,
      220,  220,  221,  221,  221,  221,  222,  222,  222,  222,

      215,  212,    0,    0,    0,  209,  218,  223,  223,  223,
      223,  224,  224,  224,  224,  221,    0,    0,  222,    0,
        0,    0,  220,    0,    0,  223,  225,  225,  225,  225,
      226,  226,  226,  226,    0,    0,    0,  224,  227,  227,
      227,  227,    0,    0,    0,  225,  228,  228,  228,  228,
      229,  229,  229,  229,  230,  230,  230,  230,  231,  231,
      231,  231,    0,    0,  226,    0,    0,    0,  227,    0,
      228,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  230,    0,    0,    0,  229,  233,  233,
      233,  233,  233,  233,  233,  234,  234,  234,  234,  234,

      234,  234,  235,    0,  235,  235,  235,  235,  235,  236,
      236,  236,  236,  237,    0,  237,    0,  237,  238,    0,
      238,    0,  238,  239,    0,  239,  239,  239,  239,  239,
      240,  240,  241,  241,  241,  241,  242,  242,  243,  243,
      244,  244,  245,  245,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,

      232,  232,  232,  232,  232,  232,  232
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
/*************************************************
 *                                               *
 *  Module: lexer.l                              *
 *  Description:                                 *
 *      Tokenizes source input and returns token *
 *      to parser on request.                    *
 *  Authors: Benders, F.J.F, Meffert, D.         *
 *           Van Oostenrijk, A.C.                *
 *  Modifications:                               *
 *                                               *
 *************************************************
 *                                               *
 *   This program is free software; you can      *
 *   redistribute it and/or modify  it under     *
 *   the terms of the GNU General Public         *
 *   License as published by the Free            *
 *   Software Foundation; either version 2       *
 *   of the License, or (at your option) any     *
 *   later version.                              *
 *                                               *
 *************************************************/
/*!LEXERL*/
#line 25 "lexer.l"

/* Include stdlib for string to number conversion routines. */
#include <stdlib.h>
/* Include errno for errno system variable. */
#include <errno.h>
/* Include string.h to use strtoul(). */
#include <string.h>
/* include assert.h for assert macro. */
#include <assert.h>
/* Include global definitions. */
#include "defs.h"
/* The token #defines are defined in tokens.h. */
#include "tokens.h"
/* Include error/warning reporting module. */
#include "errors.h"
/* Include option.h to access command line option. */
#include "options.h"

/*
 *
 * MACROS
 *
 */
#define INCPOS charPos += yyleng;


/*
 *
 * FORWARD DECLARATIONS
 *
 */
char SlashToChar( char str[] );
void AddToString( char c );

/*
 *
 * GLOBALS
 *
 */

/*
 * Tokenvalue (declared in tokens.h) is used to pass
 * literal token values to the parser.
 */
Tokenvalue tokenvalue;

/*
 * lineCount keeps track of the current line number
 * in the source input file.
 */
int lineCount;

/*
 * charPos keeps track of the current character
 * position on the current source input line.
 */
int charPos;

/* 
 * Counters used for string reading
 */
static int stringSize, stringPos;

/* 
 * commentsLevel keeps track of the current
 * comment nesting level, in order to ignore nested
 * comments properly.
 */
static int commentsLevel = 0;


/*
*
* LEXER STATES
*
*/
/* Exclusive state in which the lexer ignores all input
   until a nested comment ends. */
#define STATE_COMMENTS 1

/* Exclusive state in which the lexer returns all input
   until a string terminates with a double quote. */
#define STATE_STRING 2

/*
*
* REGULAR EXPRESSIONS
*
*/
#line 778 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 119 "lexer.l"


 /*
  *
  * KEYWORDS
  *
  */

#line 938 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 233 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 945 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 127 "lexer.l"
{ INCPOS; return KW_START; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 129 "lexer.l"
{ INCPOS; return KW_BOOL; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 130 "lexer.l"
{ INCPOS; return KW_CHAR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 131 "lexer.l"
{ INCPOS; return KW_FLOAT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 132 "lexer.l"
{ INCPOS; return KW_INT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 133 "lexer.l"
{ INCPOS; return KW_UNTYPED; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 134 "lexer.l"
{ INCPOS; return KW_VOID; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 136 "lexer.l"
{ INCPOS; return KW_BREAK; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 137 "lexer.l"
{ INCPOS; return KW_CASE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 138 "lexer.l"
{ INCPOS; return KW_DEFAULT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 139 "lexer.l"
{ INCPOS; return KW_DO; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 140 "lexer.l"
{ INCPOS; return KW_ELSE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 141 "lexer.l"
{ INCPOS; return KW_EXTERN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 142 "lexer.l"
{ INCPOS; return KW_GOTO; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 143 "lexer.l"
{ INCPOS; return KW_IF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 144 "lexer.l"
{ INCPOS; return KW_LABEL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 145 "lexer.l"
{ INCPOS; return KW_MODULE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 146 "lexer.l"
{ INCPOS; return KW_RETURN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 147 "lexer.l"
{ INCPOS; return KW_SWITCH; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 148 "lexer.l"
{ INCPOS; return KW_WHILE; }
	YY_BREAK
/*
  *
  * OPERATORS
  *
  */
case 21:
YY_RULE_SETUP
#line 157 "lexer.l"
{ INCPOS; return ARROW; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 158 "lexer.l"
{ INCPOS; return OP_EQUAL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 159 "lexer.l"
{ INCPOS; return OP_NOTEQUAL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 160 "lexer.l"
{ INCPOS; return OP_LOGICAL_AND; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 161 "lexer.l"
{ INCPOS; return OP_LOGICAL_OR; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 162 "lexer.l"
{ INCPOS; return OP_GREATEREQUAL; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 163 "lexer.l"
{ INCPOS; return OP_LESSEQUAL; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 164 "lexer.l"
{ INCPOS; return OP_BITWISE_LSHIFT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 165 "lexer.l"
{ INCPOS; return OP_BITWISE_RSHIFT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 166 "lexer.l"
{ INCPOS; return OP_ADD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 167 "lexer.l"
{ INCPOS; return OP_SUBTRACT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 168 "lexer.l"
{ INCPOS; return OP_MULTIPLY; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 170 "lexer.l"
{ INCPOS; return OP_DIVIDE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 171 "lexer.l"
{ INCPOS; return OP_NOT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 172 "lexer.l"
{ INCPOS; return OP_BITWISE_COMPLEMENT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 173 "lexer.l"
{ INCPOS; return OP_MODULUS; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 174 "lexer.l"
{ INCPOS; return OP_ASSIGN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 176 "lexer.l"
{ INCPOS; return OP_GREATER; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 177 "lexer.l"
{ INCPOS; return OP_LESS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 178 "lexer.l"
{ INCPOS; return OP_BITWISE_AND; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 179 "lexer.l"
{ INCPOS; return OP_BITWISE_OR; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 181 "lexer.l"
{ INCPOS; return OP_BITWISE_XOR; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 182 "lexer.l"
{ INCPOS; return OP_TERNARY_IF; }
	YY_BREAK
/*
  *
  * DELIMITERS
  *
  */
case 44:
YY_RULE_SETUP
#line 191 "lexer.l"
{ INCPOS; return LPAREN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 192 "lexer.l"
{ INCPOS; return RPAREN; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 193 "lexer.l"
{ INCPOS; return LBRACKET; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 194 "lexer.l"
{ INCPOS; return RBRACKET; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 195 "lexer.l"
{ INCPOS; return COLON; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 196 "lexer.l"
{ INCPOS; return SEMICOLON; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 197 "lexer.l"
{ INCPOS; return LBRACE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 198 "lexer.l"
{ INCPOS; return RBRACE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 199 "lexer.l"
{ INCPOS; return COMMA; }
	YY_BREAK
/*
  *
  * VALUE TOKENS
  *
  */
case 53:
YY_RULE_SETUP
#line 208 "lexer.l"
{ /* boolean constant */
             INCPOS;
             tokenvalue.boolvalue = TRUE;
             return( LIT_BOOL );
           }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 214 "lexer.l"
{ /* boolean constant */
             INCPOS;
             tokenvalue.boolvalue = FALSE;
             return( LIT_BOOL );
           }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 220 "lexer.l"
{ /* decimal integer constant */
             INCPOS;
             tokenvalue.uintvalue = strtoul( yytext, NULL, 10 );
             if( tokenvalue.uintvalue == -1 )
             {
                 tokenvalue.uintvalue = 0;
                 AddPosWarning( "integer literal value "
                       "too large. Zero used",
                       lineCount, charPos );
             }
             return( LIT_INT );
           }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 233 "lexer.l"
{ 
             /* hexidecimal integer constant */
             INCPOS;
             tokenvalue.uintvalue = strtoul( yytext, NULL, 16 );
             if( tokenvalue.uintvalue == -1 )
             {
                 tokenvalue.uintvalue = 0;
                 AddPosWarning( "hexadecimal integer literal value "
                                "too large. Zero used",
                                lineCount, charPos );
             }
             return( LIT_INT );
           }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 247 "lexer.l"
{ /* binary integer constant */
             INCPOS;
             tokenvalue.uintvalue = strtoul( yytext, NULL, 2 );
             if( tokenvalue.uintvalue == -1 )
             {
                 tokenvalue.uintvalue = 0;
                 AddPosWarning( "binary integer literal value too "
                                "large. Zero used" ,
                                lineCount, charPos );
             }
             return( LIT_INT );
           }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 260 "lexer.l"
{ 
 	       /* identifier */
               INCPOS;
               tokenvalue.identifier = strdup( yytext );
               return( IDENTIFIER );
             }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 267 "lexer.l"
{ 
               /* floating point number */
               INCPOS;
               if( sscanf( yytext, "%f",
					&tokenvalue.floatvalue ) == 0 )
               {
                 tokenvalue.floatvalue = 0;
                 AddPosWarning( "floating point literal value too "
                                "large. Zero used",
                                lineCount, charPos );
               }
               return( LIT_FLOAT );
             }
	YY_BREAK
/*
  *
  * CHARACTERS
  *
  */
case 60:
YY_RULE_SETUP
#line 289 "lexer.l"
{
                 INCPOS;
                 yytext[strlen(yytext)-1] = '\0';
                 tokenvalue.charvalue =
					SlashToChar( yytext+1 );
                 return( LIT_CHAR );
               }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 297 "lexer.l"
{
                 /* \B escape sequence. */
                 INCPOS;
                 yytext[strlen(yytext)-1] = '\0';
                 tokenvalue.charvalue =
					SlashToChar( yytext+1 );
                 return( LIT_CHAR );
               }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 306 "lexer.l"
{
                 /* \o escape sequence. */
                 INCPOS;
                 yytext[strlen(yytext)-1] = '\0';
                 tokenvalue.charvalue =
					SlashToChar( yytext+1 );
                 return( LIT_CHAR );
               }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 315 "lexer.l"
{
                 /* \x escape sequence. */
                 INCPOS;
                 yytext[strlen(yytext)-1] = '\0';
                 tokenvalue.charvalue =
					SlashToChar( yytext+1 );
                 return( LIT_CHAR );
               }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 324 "lexer.l"
{
                 /* Single character. */
                 INCPOS;
                 tokenvalue.charvalue = yytext[1];
                 return( LIT_CHAR );
              }
	YY_BREAK
/*
  *
  * STRINGS
  *
  */
case 65:
YY_RULE_SETUP
#line 339 "lexer.l"
{ INCPOS;
                 tokenvalue.stringvalue =
                 (char*) malloc( STRING_BLOCK );
                 memset( tokenvalue.stringvalue,
				    0, STRING_BLOCK );
                 stringSize = STRING_BLOCK;
                 stringPos = 0;
                 BEGIN STATE_STRING; /* begin of string */
               }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 349 "lexer.l"
{ 
                 INCPOS;
                 BEGIN 0;
                 /* Do not include terminating " in string */
                 return( LIT_STRING ); /* end of string */
               }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 356 "lexer.l"
{ 
                 INCPOS;
                 AddPosWarning( "strings cannot span multiple "
                                "lines", lineCount, charPos );
                 AddToString( '\n' );
               }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 363 "lexer.l"
{ 
                 /* Escape sequences in string. */
                 INCPOS; 
                 AddToString( SlashToChar( yytext ) );
               }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 369 "lexer.l"
{
                 /* \B escape sequence. */
                 INCPOS;
                 AddToString( SlashToChar( yytext ) );
               }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 375 "lexer.l"
{
                 /* \o escape sequence. */
                 INCPOS;
                 AddToString( SlashToChar( yytext ) );
               }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 381 "lexer.l"
{
                 /* \x escape sequence. */
                 INCPOS;
                 AddToString( SlashToChar( yytext ) );
               }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 387 "lexer.l"
{ 
                 /* Any other character */
                 INCPOS;
                 AddToString( yytext[0] );
               }
	YY_BREAK
/*
  *
  * LINE COMMENTS
  *
  */
case 73:
YY_RULE_SETUP
#line 400 "lexer.l"
{ ++lineCount; /* ignore comment lines */ }
	YY_BREAK
/*
  *
  * BLOCK COMMENTS
  *
  */
case 74:
YY_RULE_SETUP
#line 409 "lexer.l"
{ INCPOS;
                 ++commentsLevel;
                 BEGIN STATE_COMMENTS;
				 /* start of comments */
               }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 415 "lexer.l"
{
                INCPOS;
                ++commentsLevel; 
                /* begin of deeper nested
				   comments */
              }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 422 "lexer.l"
{ INCPOS; /* ignore all characters */ }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 424 "lexer.l"
{
                charPos = 0;
                ++lineCount; /* ignore newlines */
              }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 429 "lexer.l"
{ 
                INCPOS;
                if ( --commentsLevel == 0 ) 
                  BEGIN 0; /* end of comments*/
              }
	YY_BREAK
/*
  *
  * WHITESPACE
  *
  */
case 79:
YY_RULE_SETUP
#line 442 "lexer.l"
{ ++charPos; /* ignore whitespaces */ }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 444 "lexer.l"
{ ++lineCount;
                charPos = 0; /* ignored newlines */
              }
	YY_BREAK
/* unmatched character */
case 81:
YY_RULE_SETUP
#line 449 "lexer.l"
{ INCPOS; return yytext[0]; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 451 "lexer.l"
ECHO;
	YY_BREAK
#line 1619 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STATE_COMMENTS):
case YY_STATE_EOF(STATE_STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 233 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 233 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 232);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 451 "lexer.l"



 /*
  *
  * ADDITIONAL VERBATIM C CODE
  *
  */

/*
 * Convert slashed character (e.g. \n, \r etc.) to a
 * char value.
 * The argument is a string that start with a backslash,
 * e.g. \x2e, \o056, \n, \b11011101
 * 
 * Pre:  (for \x, \B and \o): strlen(yytext) is large
 *       enough. The regexps in the lexer take care
 *       of this.
 */
char SlashToChar( char str[] )
{
    static char strPart[20];

    memset( strPart, 0, 20 );
    
    switch( str[1] )
    {
    case '\\':
        return( '\\' );
    case '\"':
        return( '\"' );
    case '\'':
        return( '\'' );
    case 'a':
        return( '\a' );
    case 'b':
        return( '\b' );
    case 'B':

        strncpy( strPart, str+2, 8 );
        return( strtoul( yytext+2, NULL, 2 ) );
    case 'f':
        return( '\f' );
    case 'n':
        return( '\n' );
    case 'o':
        strncpy( strPart, str+2, 3 );
        return( strtoul( strPart, NULL, 8 ) );
    case 't':
        return( '\t' );
    case 'r':
        return( '\r' );
    case 'v':
        return( '\v' );
    case 'x':
        strncpy( strPart, str+2, 2 );
        return( strtoul( strPart, NULL, 16 ) );
    default:
        /* Control should never get here! */
        assert( 0 );
    }
}


/*
 * For string reading (which happens on a
 * character-by-character basis), add a character to
 * the global lexer string 'tokenvalue.stringvalue'.
 */
void AddToString( char c )
{
    if( tokenvalue.stringvalue == NULL )
    {
        /* Some previous realloc() already went wrong.
         * Silently abort.
         */
        return;
    }

    if( stringPos >= stringSize - 1 )

    {
        stringSize += STRING_BLOCK;
        DEBUG( "resizing string memory +%d, now %d bytes", 
                STRING_BLOCK, stringSize );

        tokenvalue.stringvalue =
			(char*) realloc( tokenvalue.stringvalue,
		    stringSize );
        if( tokenvalue.stringvalue == NULL )
        {
            AddPosWarning( "Unable to claim enough memory "
                           "for string storage",
						   lineCount, charPos );
            return;
        }
        memset( tokenvalue.stringvalue + stringSize
				- STRING_BLOCK, 0, STRING_BLOCK );
    }

    tokenvalue.stringvalue[stringPos] = c;
    stringPos++;
}
/*!*/

